### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by abuhman** [socs-dev-env/dosocs2#110]
I was following the installation instructions.  I did the steps for pip install and install-nomos.sh without errors.  However, if I try anything after that, such as dosocs2 newconfig or dosocs2 dbinit, there is the following error:

"ImportError: failed to find libmagic.  Check your installation"

I assume libmagic is being used but doesn't get installed during the first two steps?  Should I try installing libmagic separately from here: https://pypi.python.org/pypi/libmagic/1.0 or is there something else I should make sure to do during installation?

**Comment by ghost** [comment]
@abuhman I am all ears on knowing more. Can you do a pip freeze  and paste the list of libraries? 

Are you doing this on a mac?

**Comment by abuhman** [comment]
Pip freeze:

click==6.7
Django==1.10.4
docopt==0.6.2
dosocs2==0.16.1
Flask==0.12
itsdangerous==0.24
Jinja2==2.9.5
MarkupSafe==0.23
mysql-connector-python==2.1.3
psycopg2==2.6.2
python-magic==0.4.12
requests==2.12.4
SQLAlchemy==1.1.5
Werkzeug==0.11.15

I'm on Windows

**Comment by ghost** [comment]
#79 should fix this problem permanently

However, DoSOCSv2 is not yet Windows Native ready. There currently is a docker image for DoSOCSv2. 

Not to chase the problem away, there might be more things than just libmagic that may fail on windows.
Are you looking for a native windows compatibility of DoSOCSv2?

**Comment by ghost** [comment]
Alternately:

For Windows: https://github.com/ahupp/python-magic#dependencies

This will fix your libmagic dependencies. However, Word of caution: Do not use unknown DLLs if you do not trust them.

**Comment by abuhman** [comment]
Okay, I tried uninstalling python-magic, but now when I try to pip install DoSOCSv2 I get "  Could not find a version that satisfies the requirement DoSOCSv2-0.16.1 (from versions: )
No matching distribution found for DoSOCSv2-0.16.1"

I think it would be helpful if DoSOCSv2 was compatible with Windows if you are able to do that.  I don't have a Mac or Linux machine to run it on.

**Comment by ghost** [comment]
pip install DoSOCSv2 wont work because dosocs2 is not published to pypi python package manager. 

The only way to install dosocs2 is via GitHub instructions. No windows version anytime soon but I would strongly recommend using a virtual machine or docker image for dosocs2

**Comment by abuhman** [comment]
I found my mistake that caused the most recent "Could not find a version" error was I forgot the ./ when typing the command.

Okay, where can I find the docker image?  I'm not familiar with docker images.  The usage I would try to have of DoSOCSv2 is to import it into a different Python file and then try to call DoSOCSv2 to scan a file or folder from there.  Do you think that is doable by using the docker image?

Also, your Readme does ask users to install using "pip install ./DoSOCSv2-0.x.x" so if that's not correct would you please update the Readme for future users?

**Comment by ghost** [comment]
For the README instructions `pip install ./DoSOCSv2-0.x.x`

The intent is that a user clones this repo locally with 
`git clone https://github.com/DoSOCSv2/DoSOCSv2 DoSOCSv2`

The 2-0.x.x is to signify a major minor and release version if they exist. 

Then a pip install ./DoSOCSv2 is to tell pip to look at the location of a local package on disk. 

In your case, 

1. Navigate to the directory you clone the repo.
2. `pip install .`
3. You can also do a `pip install ./DoSOCSv2` without navigating to the directory

To Note:

pip install <package_name> goes ahead to look for a package from a repository like PyPi. 

pip install . (Install from current directory)

pip install ./SuperPackage (Install from the directory SuperPackage in current path)

**Comment by ghost** [comment]
[Here is the location to the dosocs2 docker file](https://hub.docker.com/r/ushan89/dosocsv2/
)
https://hub.docker.com/r/ushan89/dosocsv2/

What is Docker?
Container parlor tricks at their best (Personal opinion). 

How can I get started with Docker?

[Here is the link to get started in minutes](https://training.docker.com/course/developer---beginner-windows-containers)

https://training.docker.com/course/developer---beginner-windows-containers


Why docker for DoSOCSv2 on WIndows?

The current scanner `nomos` is compiled from source on linux (affectionately referred by us DoSOCSv2 members as nomossa). 

We do not compile the scanner for windows. To avoid all the hustle, using containers guarantees that the scanner works as is.

**Comment by ghost** [comment]
@abuhman closing the issue. Please do re-open if you find issues with docker
