### ISSUE TITLE
Getting CPE for file

### ISSUE THREAD

**Issue by abuhman** [socs-dev-env/dosocs2#111]
I was speaking to Dr. Germonprez, and he let me know DoSOCSv2 is able to generate a CPE for a file or folder and check whether it exists in NIST or not.  I have been looking in the code, but I have not found a part that does this.  Does DoSOCSv2 have this functionality and if so, where can I look to find it?

Thank you and have a good day.

**Comment by ghost** [comment]
I've sent you invite to a private repo. If you do not have access, please do let me know if you get access to it.

**Comment by ghost** [comment]
1) There is a connector / scanner for DoSOCSv2 for the Java Jar world. The scanner is called dependency-check. @germonprez might be able to share with you some private repo stuff. 

2) The private repo I gave you access to is a more generic version that can be used against any package assuming you make tiny implementation changes for a package by extention type. @robinagandhi might be your best bet in following what can be done to make this work for you.
