### ISSUE TITLE
Directory scans do not use package-level cache

### ISSUE THREAD

**Issue by ghost** [socs-dev-env/dosocs2#57]
For a package file (jar, tar, etc.) SHA-1 is good enough to determine that we've already scanned it. For directory scans there is no equivalent, so scanning the same directory tree multiple times will create multiple package records. We need some way to uniquely identify directories. Maybe package verification code plus hash of directory listing?

**Comment by goneall** [comment]
I suggest the PackageVerificationCode would be a good choice.  It is solving a very similar problem for the files in a package.  Since you are hashing the content of each file, I'm not sure you will need the hash of the directory listing unless you want to make sure the filenames also match.

**Comment by ghost** [comment]
Thanks for weighing in, Gary. Yes, my concern is making sure the relative path of each file is correct. If we recognize a directory as "the same" without accounting for directory structure and file names, we could end up returning a stale document that references (for example) the old locations of files that have been moved.

**Comment by goneall** [comment]
Good point - in that case hashing the file paths would be a good idea.

Be sure to normalize the text encoding of the characters (e.g. always use UTF-8) otherwise you may end up with 2 different hash values for the same characters.
