### ISSUE TITLE
Nomossa scanner

### ISSUE THREAD

**Issue by zwmcfarland** [socs-dev-env/dosocs2#59]
Maybe you already know this, but apparently you can build nomos as a standalone (separate from fossology). It appears to have the same output as nomos, without all of the requirements of postgres, and the UI components.

Source of this knowledge:
https://github.com/fossology/fossology/blob/master/src/nomos/agent/Notes

I built the scanner and played with it a bit. Seemed to work fine, and now I can use the 500k executable instead of the entire FOSSology install. 

More general information than an issue, might make the dependencies a bit more manageable. 

Side note I haven't tried doing the same with monk yet.

**Comment by ghost** [comment]
Zac, you are right. Tom is treating nomos as a standalone and has a python-wrapper for nomos. 
 You are right, having FOSSology as a dependency makes it complex when  NOMOS does the job. 

Given, cosmology is currently not as modular as we expect it to be, I have been hearing that a new version of fossology is on the horizon.

**Comment by ttgurney** [comment]
Thanks Zac. I always wondered about that `nomossa

**Comment by ghost** [comment]
Thanks Zac. I always wondered about that `nomossa` executable included with the FOSSology distribution.

The remaining issue is that there is no separate `nomossa` distribution. Only a `fossology-nomos` package is available (here: http://www.fossology.org/releases/2.6.2/Ubuntu/14.04/) and it has `fossology-common` as a hard dependency. This will be an issue if I ever want to package dosocs2 as a .deb and I want to specify the dependencies.
I suppose I could volunteer to maintain a `fossology-nomossa` package...

What were the build dependencies for `nomossa`? I'm going to guess just `libc` and maybe `libglib-2.0`? Many thanks.

**Comment by ghost** [comment]
Nevermind, I have figured it out:

```
$ ldd nomossa
    linux-vdso.so.1 =>  (0x00007fff155f8000)
    libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007fada5268000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fada4ea3000)
    libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fada4c65000)
    libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fada4a47000)
    /lib64/ld-linux-x86-64.so.2 (0x00007fada5570000)
```

And I've found the `Makefile.sa` that allows building the standalone executable. Sweet! Now I just have to figure out the best way to "link it in" as a dependency.

**Comment by zwmcfarland** [comment]
I just installed glib2-devel (on centOS) and then overwrote the make file with the .sa version.

**Comment by ghost** [comment]
Finally got to this one. Check out `scripts/install-nomos.sh`. Not sure why I didn't think of this sooner!
