### ISSUE TITLE
Update maintainer list

### ISSUE THREAD

**Issue by ghost** [socs-dev-env/dosocs2#70]
With my departure from the team, the maintainer info in README.md needs to be updated to point to Uday and Josiah instead of me.

**Comment by zwmcfarland** [comment]
Just a thought.

The readme could point to members of the DoSOCSv2 GitHub organization, then people can come and go and you won't have to make "code" changes.

https://github.com/orgs/DoSOCSv2/people

**Comment by ghost** [comment]
Great idea. The other members of the org @germonprez @UShan89 @spacetag will have to set their membership status to public first... unless I can do that for them. I don't think I can.
